Repository rcbops/zigzag, pull requests merged in 2018-08, with the labels that each got.

#43 ASC-890 base GitHub link on SHA
  tests/unit/test_link_generation_facade.py
  zigzag/link_generation_facade.py
  zigzag/zigzag_test_log.py
Labels: v0.11.0

#44 ASC-775 Integration Tests for Failure Output
  tests/integration/conftest.py
  tests/integration/test_failure_output.py
Labels: v0.12.0

#45 ASC-774 Add Requirement Linking Integration Tests
  tests/integration/conftest.py
  tests/integration/test_failure_output.py
  tests/integration/test_requirement_linking.py
Labels: v0.12.0

#47 ASC-776 Add Negative Scenario Integration Tests
  tests/integration/conftest.py
  tests/integration/test_negative.py
Labels: v0.12.0

#48 ASC-441 Add Test Case Rename/Move Integration Tests
  tests/integration/conftest.py
  tests/integration/test_basic.py
Labels: v0.12.0

#49 ASC-796 Add Failure Linking Integration Tests
  tests/integration/conftest.py
  tests/integration/test_failure_output.py
  tests/integration/test_github_linking.py
Labels: v0.12.0

#50 ASC-864 Fix Crash on Failure Attachment
  Makefile
  docs/release_process.rst
  tests/data/junit.xml.j2
  tests/integration/conftest.py
  tests/integration/test_negative.py
  tox.ini
  zigzag/zigzag_test_log.py
Labels: v0.11.1

#51 ASC-867 Improve Failure Output Truncation
  tests/integration/test_failure_output.py
  tests/unit/test_zigzag_test_log.py
  zigzag/zigzag_test_log.py
Labels: v0.12.0
